export const FruitStage = {
  BUD_FRUIT: "BUD_FRUIT",
  FLOWER_FRUIT: "FLOWER_FRUIT",
  SET_FRUIT: "SET_FRUIT",
  BREAKER_STAGE_FRUIT: "BREAKER_STAGE_FRUIT",
  MATURE_GREEN_FRUIT: "MATURE_GREEN_FRUIT",
  HARVESTABLE_FRUIT: "HARVESTABLE_FRUIT",

  BUD: "BUD",
  FLOWER: "FLOWER",
  SET: "SET",
  BREAKER_STAGE: "BREAKER_STAGE",
  MATURE_GREEN: "MATURE_GREEN",
  HARVESTABLE: "HARVESTABLE",
};
